Executing script: C:\Users\Arellano\Documents\GitHub\RandomScripts\functions.py
Script arguments: 
Output:
Traceback (most recent call last):
  File "C:\Users\Arellano\Documents\GitHub\RandomScripts\functions.py", line 11, in <module>
    arg1 = sys.argv[1]
IndexError: list index out of range

